services:
  # Backend Web Service
  - type: web
    name: inventory-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: b13cdabd569515d19c0a5977a530ad6b6a0dcaab319ebc0ee5be742cb8e527c8
      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: inventory-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: inventory-db
          property: database

databases:
  # PostgreSQL Database
  - name: inventory-db
    databaseName: storeflow
    plan: free
    region: singapore
